name: Deploy to cPanel via SFTP

on:
  push:
    branches:
      - main

jobs:
  sftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository tourism
        uses: actions/checkout@v4

      - name: Deploy via SFTP (SSH key)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.smartv-demo.com
          username: tourism@smartv-demo.com
          protocol: sftp
          port: 22
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}
          local-dir: ./
          server-dir: public_html/tourism_company/
          log-level: verbose
